#ifndef H_INSTRUCTION
#define H_INSTRUCTION

enum Addressing{
  NA_ADDRESSING = 0,
  IMPLIED,
  ACCUMULATOR,
  IMMEDIATE,
  ZERO_PAGE, ZERO_PAGE_X, ZERO_PAGE_Y,
  RELATIVE,
  ABSOLUTE, ABSOLUTE_X, ABSOLUTE_Y,
  INDIRECT, INDIRECT_X, INDIRECT_Y
};

enum BaseName{
  NA_BASE_NAME = 0,
  //Load
  LDA, LDX, LDY, // 1 ~ 3
  //Store
  STA, STX, STY, TAX, TAY, TSX, TXA, TXS, TYA, // 4 ~ 12
  //Calculation
  ADC, AND, ASL, BIT, CMP, CPX, CPY, DEC, DEX, DEY, EOR, INC, INX, INY, LSR, ORA, ROL, ROR, SBC, // 13 ~ 31
  //Stack
  PHA, PHP, PLA, PLP, // 32 ~ 35
  //Jump
  JMP, JSR, RTS, RTI, // 36 ~ 39
  //Branch
  BCC, BCS, BEQ, BMI, BNE, BPL, BVC, BVS, // 40 ~ 47
  //Flag
  CLC, CLD, CLI, CLV, SEC, SED, SEI, // 48 ~ 54
  //Other
  BRK, NOP
};

typedef struct opecode_list{
  BaseName base;
  Addressing add;
  uint8_t cycles;
}opecode_list_t;

opecode_list_t ope_list[]={
  {BRK, IMPLIED, 2},                //0x00
  {ORA, INDIRECT_X, 1},             //0x01
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x02
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x03
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x04
  {ORA, ZERO_PAGE, 2},              //0x05
  {ASL, ZERO_PAGE, 2},              //0x06
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x07
  {PHP, IMPLIED, 2},                //0x08
  {ORA, IMMEDIATE, 2},              //0x09
  {ASL, ACCUMULATOR, 1},            //0x0A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x0B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x0C
  {ORA, ABSOLUTE, 1},               //0x0D
  {ASL, ABSOLUTE, 2},               //0x0E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x0F

  {BPL, RELATIVE, 1},               //0x10
  {ORA, INDIRECT_Y, 1},             //0x11
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x12
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x13
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x14
  {ORA, ZERO_PAGE_X, 2},            //0x15
  {ASL, ZERO_PAGE_X, 2},            //0x16
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x17
  {CLC, IMPLIED, 2},                //0x18
  {ORA, ABSOLUTE_Y, 2},             //0x19
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x1A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x1B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x1C
  {ORA, ABSOLUTE_X, 1},             //0x1D
  {ASL, ABSOLUTE_X, 2},             //0x1E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x1F

  {JSR, ABSOLUTE, 1},               //0x20
  {AND, INDIRECT_X, 1},             //0x21
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x22
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x23
  {BIT, ZERO_PAGE, 0}, //0x24
  {AND, ZERO_PAGE, 2},            //0x25
  {ROL, ZERO_PAGE, 2},            //0x26
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x27
  {PLP, IMPLIED, 2},                //0x28
  {AND, IMMEDIATE, 2},             //0x29
  {ROL, ACCUMULATOR, 0}, //0x2A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x2B
  {BIT, ABSOLUTE, 0}, //0x2C
  {AND, ABSOLUTE, 1},             //0x2D
  {ROL, ABSOLUTE, 2},             //0x2E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x2F

  {BMI, RELATIVE, 2}, //0x30
  {AND, INDIRECT_Y, 2}, //0x31
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x32
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x33
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x34
  {AND, ZERO_PAGE_X, 0}, //0x35
  {ROL, ZERO_PAGE_X, 2}, //0x36
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x37
  {SEC, IMPLIED, 0}, //0x38
  {AND, ABSOLUTE_Y, 2}, //0x39
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x3A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x3B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x3C
  {AND, ABSOLUTE_X, 0}, //0x3D
  {ROL, ABSOLUTE_X, 2}, //0x3E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x3F

  {RTI, IMPLIED, 2}, //0x40
  {EOR, INDIRECT_X, 2}, //0x41
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x42
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x43
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x44
  {EOR, ZERO_PAGE, 0}, //0x45
  {LSR, ZERO_PAGE, 2}, //0x46
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x47
  {PHA, IMPLIED, 0}, //0x48
  {EOR, IMMEDIATE, 2}, //0x49
  {LSR, ACCUMULATOR, 2}, //0x4A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x4B
  {JMP, ABSOLUTE, 2}, //0x4C
  {EOR, ABSOLUTE, 0}, //0x4D
  {LSR, ABSOLUTE, 2}, //0x4E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x4F

  {BVC, RELATIVE, 2}, //0x50
  {EOR, INDIRECT_Y, 2}, //0x51
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x52
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x53
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x54
  {EOR, ZERO_PAGE_X, 0}, //0x55
  {LSR, ZERO_PAGE_X, 2}, //0x56
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x57
  {CLI, IMPLIED, 0}, //0x58
  {EOR, ABSOLUTE_Y, 2}, //0x59
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x5A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x5B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x5C
  {EOR, ABSOLUTE_X, 2}, //0x5D
  {LSR, ABSOLUTE_X, 2}, //0x5E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x5F

  {RTS, IMPLIED, 2}, //0x60
  {ADC, INDIRECT_X, 2}, //0x61
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x62
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x63
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x64
  {ADC, ZERO_PAGE, 0}, //0x65
  {ROR, ZERO_PAGE, 2}, //0x66
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x67
  {PLA, IMPLIED, 0}, //0x68
  {ADC, IMMEDIATE, 2}, //0x69
  {ROR, ACCUMULATOR, 2}, //0x6A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x6B
  {JMP, INDIRECT, 2}, //0x6C
  {ADC, ABSOLUTE, 0}, //0x6D
  {ROR, ABSOLUTE, 2}, //0x6E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x6F

  {BVS, RELATIVE, 2}, //0x70
  {ADC, INDIRECT_Y, 2}, //0x71
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x72
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x73
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x74
  {ADC, ZERO_PAGE_X, 0}, //0x75
  {ROR, ZERO_PAGE_X, 2}, //0x76
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x77
  {SEI, IMPLIED, 0}, //0x78
  {ADC, ABSOLUTE_Y, 2}, //0x79
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x7A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x7B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x7C
  {ADC, ABSOLUTE_X, 0}, //0x7D
  {ROR, ABSOLUTE_X, 2}, //0x7E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x7F

  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x80
  {STA, INDIRECT_X, 2}, //0x81
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x82
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x83
  {STY, ZERO_PAGE, 2}, //0x84
  {STA, ZERO_PAGE, 0}, //0x85
  {STX, ZERO_PAGE, 2}, //0x86
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x87
  {DEY, IMPLIED, 0}, //0x88
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x89
  {TXA, IMPLIED, 2}, //0x8A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x8B
  {STY, ABSOLUTE, 2}, //0x8C
  {STA, ABSOLUTE, 0}, //0x8D
  {STX, ABSOLUTE, 2}, //0x8E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x8F

  {BCC, RELATIVE, 2}, //0x90
  {STA, INDIRECT_Y, 2}, //0x91
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x92
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x93
  {STY, ZERO_PAGE_X, 2}, //0x94
  {STA, ZERO_PAGE_X, 0}, //0x95
  {STX, ZERO_PAGE_Y, 2}, //0x96
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x97
  {TYA, IMPLIED, 0}, //0x98
  {STA, ABSOLUTE_Y, 2}, //0x99
  {TXS, IMPLIED, 2}, //0x9A
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x9B
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x9C
  {STA, ABSOLUTE_X, 0}, //0x9D
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x9E
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0x9F

  {LDY, IMMEDIATE, 2}, //0xA0
  {LDA, INDIRECT_X, 2}, //0xA1
  {LDX, IMMEDIATE, 0}, //0xA2
  {NA_BASE_NAME, NA_ADDRESSING, 0},  //0xA3
  {LDY, ZERO_PAGE, 2}, //0xA4
  {LDA, ZERO_PAGE, 0}, //0xA5
  {LDX, ZERO_PAGE, 2}, //0xA6
  {NA_BASE_NAME, NA_ADDRESSING, 0},  //0xA7
  {TAY, IMPLIED, 0}, //0xA8
  {LDA, IMMEDIATE, 2}, //0xA9
  {TAX, IMPLIED, 2}, //0xAA
  {NA_BASE_NAME, NA_ADDRESSING, 0},  //0xAB
  {LDY, ABSOLUTE, 2}, //0xAC
  {LDA, ABSOLUTE, 0}, //0xAD
  {LDX, ABSOLUTE, 2}, //0xAE
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xAF

  {BCS, RELATIVE, 2}, //0xB0
  {LDA, INDIRECT_X, 2}, //0xB1
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xB2
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xB3
  {LDY, ZERO_PAGE_X, 2}, //0xB4
  {LDA, ZERO_PAGE_X, 0}, //0xB5
  {LDX, ZERO_PAGE_Y, 2}, //0xB6
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xB7
  {CLV, IMPLIED, 0}, //0xB8
  {LDA, ABSOLUTE_Y, 2}, //0xB9
  {TSX, IMPLIED, 2}, //0xBA
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xBB
  {LDY, ABSOLUTE_X, 2}, //0xBC
  {LDA, ABSOLUTE_X, 0}, //0xBD
  {LDX, ABSOLUTE_Y, 2}, //0xBE
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xBF

  {CPY, IMMEDIATE, 2}, //0xC0
  {CMP, INDIRECT_X, 2}, //0xC1
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xC2
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xC3
  {CPY, ZERO_PAGE, 2}, //0xC4
  {CMP, ZERO_PAGE, 0}, //0xC5
  {DEC, ZERO_PAGE, 2}, //0xC6
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xC7
  {INY, IMPLIED, 0}, //0xC8
  {CMP, IMMEDIATE, 2}, //0xC9
  {DEX, IMPLIED, 2}, //0xCA
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xCB
  {CPY, ABSOLUTE, 2}, //0xCC
  {CMP, ABSOLUTE, 0}, //0xCD
  {DEC, ABSOLUTE, 2}, //0xCE
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xCF

  {BNE, RELATIVE, 2}, //0xD0
  {CMP, INDIRECT_Y, 2}, //0xD1
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xD2
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xD3
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xD4
  {CMP, ZERO_PAGE_X, 0}, //0xD5
  {DEC, ZERO_PAGE_X, 2}, //0xD6
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xD7
  {CLD, IMPLIED, 0}, //0xD8
  {CMP, ABSOLUTE_Y, 2}, //0xD9
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xDA
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xDB
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xDC
  {CMP, ABSOLUTE_X, 0}, //0xDD
  {DEC, ABSOLUTE_X, 2}, //0xDE
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xDF

  {CPX, IMMEDIATE, 2}, //0xE0
  {SBC, INDIRECT_X, 2}, //0xE1
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xE2
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xE3
  {CPX, ZERO_PAGE, 2}, //0xE4
  {SBC, ZERO_PAGE, 0}, //0xE5
  {INC, ZERO_PAGE, 2}, //0xE6
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xE7
  {INX, IMPLIED, 0}, //0xE8
  {SBC, IMMEDIATE, 2}, //0xE9
  {NOP, IMPLIED, 2}, //0xEA
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xEB
  {CPX, ABSOLUTE, 2}, //0xEC
  {SBC, ABSOLUTE, 0}, //0xED
  {INC, ABSOLUTE, 2}, //0xEE
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xEF

  {BEQ, RELATIVE, 2}, //0xF0
  {SBC, INDIRECT_Y, 2}, //0xF1
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xF2
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xF3
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xF4
  {SBC, ZERO_PAGE_X, 0}, //0xF5
  {INC, ZERO_PAGE_X, 2}, //0xF6
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xF7
  {SED, IMPLIED, 0}, //0xF8
  {SBC, ABSOLUTE_Y, 2}, //0xF9
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xFA
  {NA_BASE_NAME, NA_ADDRESSING, 0},//0xFB
  {NA_BASE_NAME, NA_ADDRESSING, 0}, //0xFC
  {SBC, ABSOLUTE_X, 0}, //0xFD
  {INC, ABSOLUTE_X, 2}, //0xFE
  {NA_BASE_NAME, NA_ADDRESSING, 0} //0xFF
};

#endif